<<<<<<< HEAD
services:
    postgres:
        build: 
            context: ./app/userdb
        restart: unless-stopped
        image: postgres
        container_name: 'postgres'
        environment:
            - POSTGRES_DB=ANIMALDEXdb
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - "5432:5432"  
        volumes:
           - db-data:/var/lib/postgresql/data
    pgadmin:
        image: dpage/pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=ale@gmail.com
            - PGADMIN_DEFAULT_PASSWORD=9900
        ports:
            - "5050:80"
    recognizer:
        build:
            context: ./app/recognizer
        image: python
        ports:
            - "5000:5000"
    certificate:
        build:
            context: "./app/certificate/certificate"
        ports:
            - "8080:8080"
volumes:
    db-data:
        driver: local 
=======
services:
  postgres:
    build: 
      context: ./app/db
    restart: unless-stopped
    image: postgres
    container_name: 'postgres-animaldex'
    environment:
      - POSTGRES_DB=ANIMALDEXdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"  
    volumes:
      - db-data-animaldex:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=ale@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=9900
    ports:
      - "5050:80"

  recognizer:
    build:
      context: ./app/recognizer
    image: python
    ports:
      - "5000:5000"

  certificate:
    build:
      context: "./app/certificate/certificate"
    ports:
      - "8080:8080"

volumes:
  db-data-animaldex:
    driver: local
>>>>>>> 85863a1ceaaaf9493861c4554033159d26736d59
