services:
    postgres:
        build: 
            context: ./userdb
        restart: unless-stopped
        image: postgres
        container_name: 'postgres'
        environment:
            - POSTGRES_DB=ANIMALDEXdb
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - "5432:5432"  
        volumes:
           - db-data:/var/lib/postgresql/data
    pgadmin:
        image: dpage/pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=ale@gmail.com
            - PGADMIN_DEFAULT_PASSWORD=9900
        ports:
            - "5050:80"
    recognizer:
        build:
            context: ./recognizer
        image: python
        ports:
            - "5000:5000"
    certificate:
        build:
            context: "./certificate"
        ports:
            - "7777:7777"
    nodejs:
        build: ./FrontendUser
        ports:
            - "3000:3000"
volumes:
    db-data:
        driver: local 
