version: '3.8'

services:
  postgres:
    build: 
      context: ./db
    restart: unless-stopped
    image: postgres
    environment:
      - POSTGRES_DB=CentralDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
    - "5433"
    ports:
      - "5433:5433"
    command: -p 5433  
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - pg_network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=ale@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=9900
    ports:
      - "5051:80"
    networks:
      - pg_network

  logic:
    build:
      context: "./logic"
    ports: 
      - "6039:6039"
    networks:
      - pg_network

networks:
  pg_network:
    driver: bridge

volumes:
  db-data:
    driver: local
